AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  Exclude:
    - db/schema.rb

Rails:
  Enabled: true

# RAILS4: Enable after Rails 4 upgrade.
Rails/ApplicationRecord:
  Enabled: false

# RAILS4: Enable after Rails 4 upgrade.
Rails/FindBy:
  Enabled: false

# RAILS4: Enable after Rails 4 upgrade.
Rails/ActionFilter:
  Enabled: false

# RAILS4: Enable after Rails 4 upgrade.
Rails/HttpPositionalArguments:
  Enabled: false

# Allow `update_attribute`, we know when to use it.
Rails/SkipsModelValidations:
  Enabled: false

# Do not sort gems in Gemfile, since we are grouping them by functionality.
Bundler/OrderedGems:
  Enabled: false

# Trailing commas are required on multiline method arguments.
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

# Trailing commas are required in multiline arrays and hashes.
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

# Trailing commas are required in multiline arrays and hashes.
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

# Allow template token (that are used in translation keys).
Style/FormatStringToken:
  EnforcedStyle: template

# Allow indenting multiline chained operations.
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

# Limit method length (default is 10).
Metrics/MethodLength:
  Max: 15

# Limit class length (default is 100).
Metrics/ClassLength:
  Max: 200

# Do not require `# frozen_string_literal: true` at the top of every file.
FrozenStringLiteralComment:
  Enabled: false

# Allow ASCII comments (e.g "…").
Style/AsciiComments:
  Enabled: false

# Do not comment the class we create, since the name should be self explanatory.
Documentation:
  Enabled: false

# Do not verify the length of the blocks in the specs.
Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - engines/maker/spec/**/*
    - engines/shopper/spec/**/*
    - lib/tasks/**/*
    - app/admin/**/*
  ExcludedMethods:
    - included

# Allow any number of keyword arguments in methods.
Metrics/ParameterLists:
  CountKeywordArgs: false

# Do not prefer `lambda` to `->` for DSLs.
Style/Lambda:
  Exclude:
    - app/graph/**/*

# Allow indenting multiline chained operations.
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

# Prefer `== 0`, `< 0`, `> 0` to `zero?`, `negative?` or `positive?`,
# since they don't exist before Ruby 2.3 or Rails 5 and can be ambiguous.
Style/NumericPredicate:
  EnforcedStyle: comparison

# This cop incorrectly assumes that `Rails.root.join('foo', 'bar')` works better
# under Windows than `Rails.root.join('foo/bar')`.
# Disabled until https://github.com/bbatsov/rubocop/issues/5823 is fixed
Rails/FilePath:
  Enabled: false
